pipeline {
    agent any

    tools {
        maven 'Maven 3.9.6'      // Replace with the name of your Maven installation in Jenkins
        jdk 'Java 17'            // Replace with your JDK version name in Jenkins
    }

    environment {
        ALLURE_RESULTS = "allure-results"
        ALLURE_REPORT = "allure-report"
    }

    stages {

        stage('Clean Workspace') {
            steps {
                deleteDir()
            }
        }

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                sh 'mvn clean test -Dtestdata=testdata.yaml'
            }
        }

        stage('Generate Allure Report') {
            steps {
                sh 'mvn allure:report'
            }
        }

        stage('Serve Allure Report') {
            steps {
                allure includeProperties: false, jdk: '', results: [[path: "${ALLURE_RESULTS}"]]
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: '**/target/*.log', fingerprint: true
            junit 'target/surefire-reports/*.xml'
        }

        success {
            echo '✅ BUILD PASSED'
        }

        failure {
            echo '❌ BUILD FAILED'
        }
    }
}